sudo: required
services:
  - docker

before_install:
  - docker build -t ochuko3d/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true ochuko3d/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-eu-west-1-364263040368"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

